"""
Plain Text Report Generator.

Generates human-readable text reports.
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

from ethiscan.core.models import ScanResult, Vulnerability


class TxtReporter:
    """
    Plain text report generator.
    
    Produces readable text reports suitable for terminal viewing
    or embedding in documentation.
    """
    
    def __init__(self) -> None:
        """Initialize the text reporter."""
        self.extension = ".txt"
    
    def generate(self, result: ScanResult, output_path: str) -> str:
        """
        Generate a text report.
        
        Args:
            result: Scan result to report.
            output_path: Base output path (without extension).
            
        Returns:
            Path to the generated report file.
        """
        file_path = f"{output_path}{self.extension}"
        
        lines = []
        
        # Header
        lines.append("=" * 70)
        lines.append("ETHISCAN - VULNERABILITY SCAN REPORT")
        lines.append("=" * 70)
        lines.append("")
        
        # Target Information
        lines.append("TARGET INFORMATION")
        lines.append("-" * 40)
        lines.append(f"URL:           {result.target.url}")
        if result.target.ip_address:
            lines.append(f"IP Address:    {result.target.ip_address}")
        if result.target.server:
            lines.append(f"Server:        {result.target.server}")
        if result.target.technologies:
            lines.append(f"Technologies:  {', '.join(result.target.technologies)}")
        lines.append("")
        
        # Scan Details
        lines.append("SCAN DETAILS")
        lines.append("-" * 40)
        lines.append(f"Scan Time:     {result.scan_time.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"Duration:      {result.duration:.2f} seconds")
        lines.append(f"Scan Type:     {'ACTIVE' if result.active_scan else 'PASSIVE'}")
        lines.append(f"Modules Run:   {', '.join(result.modules_run)}")
        lines.append("")
        
        # Summary
        lines.append("VULNERABILITY SUMMARY")
        lines.append("-" * 40)
        lines.append(f"Total:    {result.vulnerability_count}")
        lines.append(f"Critical: {result.critical_count}")
        lines.append(f"High:     {result.high_count}")
        lines.append(f"Medium:   {result.medium_count}")
        lines.append(f"Low:      {result.low_count}")
        lines.append(f"Info:     {result.info_count}")
        lines.append("")
        
        # Vulnerabilities
        if result.vulnerabilities:
            lines.append("=" * 70)
            lines.append("VULNERABILITY DETAILS")
            lines.append("=" * 70)
            lines.append("")
            
            # Sort by severity
            severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
            sorted_vulns = sorted(
                result.vulnerabilities,
                key=lambda v: severity_order.index(v.severity)
            )
            
            for i, vuln in enumerate(sorted_vulns, 1):
                lines.append(f"[{i}] {vuln.name}")
                lines.append("-" * 50)
                lines.append(f"Severity:    {vuln.severity}")
                lines.append(f"Module:      {vuln.module}")
                if vuln.cwe_id:
                    lines.append(f"CWE:         {vuln.cwe_id}")
                lines.append("")
                lines.append("Description:")
                lines.append(self._wrap_text(vuln.description, 60))
                lines.append("")
                if vuln.evidence:
                    lines.append("Evidence:")
                    lines.append(self._wrap_text(vuln.evidence, 60))
                    lines.append("")
                if vuln.fix:
                    lines.append("Recommendation:")
                    lines.append(self._wrap_text(vuln.fix, 60))
                    lines.append("")
                if vuln.references:
                    lines.append("References:")
                    for ref in vuln.references:
                        lines.append(f"  - {ref}")
                    lines.append("")
                lines.append("")
        else:
            lines.append("[+] No vulnerabilities found!")
            lines.append("")
        
        # Footer
        lines.append("=" * 70)
        lines.append("Report generated by EthiScan")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("=" * 70)
        
        # Write to file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        
        return file_path
    
    def _wrap_text(self, text: str, width: int) -> str:
        """Wrap text to specified width with indentation."""
        words = text.split()
        lines = []
        current_line = "  "
        
        for word in words:
            if len(current_line) + len(word) + 1 <= width:
                current_line += word + " "
            else:
                lines.append(current_line.rstrip())
                current_line = "  " + word + " "
        
        if current_line.strip():
            lines.append(current_line.rstrip())
        
        return "\n".join(lines)
